app.openapi.dev-url=http://localhost:8080/green-project
app.openapi.prod-url=https://noncbsuat.bankofbaroda.co.in/green-project

spring.application.name=green-project

server.port = 8080

server.servlet.context-path=/green-project

springdoc.swagger-ui.path=/green-project-swagger-ui
springdoc.api-docs.path=/green-project-swagger-docs
#springdoc.api-docs.apth=/green-project-swagger-docs
springdoc.packages-to-scan=com.bob.app.api.rest
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true


# create and drop tables
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=none

# Oracle settings
#Local
spring.datasource.url=jdbc:oracle:thin:@172.16.251.117:1525/NONCBSDB
spring.datasource.username=noncbsdb
spring.datasource.password=Bank_12345

#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
#spring.datasource.username=system
#spring.datasource.password=admin123

#Prod
#spring.datasource.url=jdbc:oracle:thin:@172.16.18.158:1525/NONCBSDB
#spring.datasource.username=noncbs
#spring.datasource.password=Bob_1234

#inapps.bankofbaroda url
#spring.datasource.url=jdbc racle:thin:@172.16.19.150:1535/FDODB
#spring.datasource.username=fbodbusr
#spring.datasource.password=Bank_1234
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver


#springdoc.api-docs.path = /bob-openapi

spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

#spring.liquibase.change-log=classpath:db/changelog-master.xml
#logging.level.liquibase = INFO

#60 seconds
spring.datasource.hikari.connection-timeout=60000
#3 second
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
#5 minutes
spring.datasource.hikari.idle-timeout=300000
#30 minutes
spring.datasource.hikari.max-lifetime=1800000
#keep trying
spring.datasource.hikari.initialization-fail-timeout=-1
#server.servlet.session.timeout=30m

# Set the server port
#cors.allowedOrigins = https://noncbsdev.bankofbaroda.co.in:443
#server.port=8080




#CBS UAT
#fi.url=https://FINSITAP201.bankofbaroda.co.in:16000/FISERVLET/fihttp

fi.url = https://cbdrpt001.bankofbaroda.co.in:22000/FISERVLET/fihttp
#AADHAARSTMT|43760100005254|01-12-2024|04-12-2024|


fi.dedup=<FIXML xsi:schemaLocation="http://www.finacle.com/fixml executeFinacleScript.xsd" xmlns="http://www.finacle.com/fixml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Header><RequestHeader><MessageKey><RequestUUID>PARAM_REQ_ID</RequestUUID><ServiceRequestId>executeFinacleScript</ServiceRequestId><ServiceRequestVersion>10.2</ServiceRequestVersion><ChannelId>OPL</ChannelId><LanguageId></LanguageId></MessageKey><RequestMessageInfo><BankId></BankId><TimeZone></TimeZone><EntityId></EntityId><EntityType></EntityType><ArmCorrelationId></ArmCorrelationId><MessageDateTime>2023-08-04T11:51:21.761</MessageDateTime></RequestMessageInfo><Security><Token><PasswordToken><UserId></UserId><Password></Password></PasswordToken></Token><FICertToken></FICertToken><RealUserLoginSessionId></RealUserLoginSessionId><RealUser></RealUser><RealUserPwd></RealUserPwd><SSOTransferToken></SSOTransferToken></Security></RequestHeader></Header><Body><executeFinacleScriptRequest><ExecuteFinacleScriptInputVO><requestId>Aadhaar_API_AcctStatement.scr</requestId></ExecuteFinacleScriptInputVO><executeFinacleScript_CustomData><MSG>PARAM_ACCT</MSG><CHANNEL>OPL</CHANNEL><UID>PARAM_UID</UID></executeFinacleScript_CustomData></executeFinacleScriptRequest></Body></FIXML>